"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

const client = new ApolloClient({
  uri: "http://localhost:3000/api/graphql",
  cache: new InMemoryCache(),
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "sample next",
  description: "Generated by sample next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <div className={`p-10`}>{children}</div>
        </ApolloProvider>
      </body>
    </html>
  );
}
